learning_log/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('learning_logs.urls', namespace='learning_logs')),
]

learning_logs/urls.py
""""define url mode in learning_logs"""
from django.conf.urls import url
from . import views

urlpatterns = [
    #main page
    url(r'^$', views.index, name='index'),

    #all topics
    url(r'^topics/$', views.topics, name='topics'),

    #specific topic
    url(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),

    #new topic
    url(r'^new_topic/$', views.new_topic, name='new_topic'),

    #new entry
    url(r'^new_entry/(?P<topic_id>\d+)/$' , views.new_entry, name='new_entry'),
]

learning_logs/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Topic(models.Model):
    """user learning topic"""
    text = models.CharField( max_length = 200)
    date_added = models.DateTimeField(auto_now_add = True)

    def __unicode__(self):
        """return model's string """
        return self.text

class Entry(models.Model):
    """the entry of some learning topic"""
    topic = models.ForeignKey(Topic)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add = True)

    class Meta:
        verbose_name_plural = 'entries'

    def __unicode__(self):
        """return model's string"""
        return self.text[:50] + '...'

learning_logs/forms.py
from django import forms

from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text':''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text':''}
        widgets = {'text': forms.Textarea(attrs={'col':80})}

learning_logs/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from .models import Topic
from .forms import TopicForm, EntryForm

# Create your views here.

def index(request):
    """learning log home"""
    return render(request, 'learning_logs/index.html')

def topics(request):
    """display all topics"""
    topics = Topic.objects.order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html',context)

def topic(request,topic_id):
    """display specific topic"""
    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic':topic, 'entries':entries}
    return render(request, 'learning_logs/topic.html', context)

def new_topic(request):
    """add new topic"""
    if request.method != 'POST':
        form = TopicForm()
    else:
        form = TopicForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)

def new_entry(request, topic_id):
    """add new entry"""
    topic = Topic.objects.get(id = topic_id)
    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(request.POST)
        if form.is_valid():
            new_entry = form.save(commit = False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic_id]))
    context = {'topic': topic, 'form':form}
    return render(request, 'learning_logs/new_entry.html', context)

learning_logs/templates/learning_logs/base.html
<p>
    <a href="{% url 'learning_logs:index' %}"> Learning Log </a> - 
    <a href="{% url 'learning_logs:topics' %}"> Topics </a>
</p>
{% block content %}{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}
{% block content %}
<p>Learning Log helps you keep track of you learning, for any topic you are learing about</p>
{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}
{% block content %}
<p>
    <a href="{% url 'learning_logs:topic' topic.id %}"> {{ topic }} </a>
</p>
<p>Add a new entry:</p>
<form action="{% url 'learning_logs:new_entry' topic.id %}" method='POST'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit"> add entry </button>
</form>
{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% block content %}
<p> Add a new topic: </p>
<form action="{% url 'learning_logs:new_topic' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">add topic</button>
</form>
{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends  "learning_logs/base.html" %}

{% block content %}
<p>Topic:{{ topic }}</p>
<p> Entries </p>
<ul>
{% for entry in entries %}
    <li> 
        <p>{{ entry.date_added | date:'M d,Y H:i' }}</p>
        <p>{{ entry.text | linebreaks }}</p>
    </li>
{% empty %}
    <li> There is no entries for this topic yet. 
    </li>
{% endfor %}
</ul>
<p><a href="{% url 'learning_logs:new_entry' topic.id %}">Add a new entry</a></p>
{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}
{% block content %}
<p>Topics</p>
<ul>
{% for topic in topics %}
    <li><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></li>
{% empty %}
    <li>No topics have been added yet. </li>
{% endfor %}
</ul>
<a href="{% url 'learning_logs:new_topic' %}">Add a new topic</a>
{% endblock content %}